"""
export_report.py — 结构化数据导出与报告生成工具

功能：
  1. 从 data/structured/{name}.json 读取采集数据
  2. 导出 CSV、HTML、JSON 三种格式
  3. 输出到 data/reports/

CSV 字段：title, date, issuer, region, budget, detail_url
"""

from __future__ import annotations

import argparse
import csv
import html
import json
import logging
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

STRUCTURED_DIR = PROJECT_ROOT / "data" / "structured"
REPORTS_DIR = PROJECT_ROOT / "data" / "reports"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("export_report")

CSV_FIELDS = ["title", "date", "issuer", "region", "budget", "detail_url"]

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         background: #f5f7fa; color: #2c3e50; padding: 24px; }}
  .container {{ max-width: 1200px; margin: 0 auto; }}
  h1 {{ font-size: 1.5rem; margin-bottom: 8px; color: #1a5276; }}
  .meta {{ color: #7f8c8d; font-size: 0.85rem; margin-bottom: 20px; }}
  .meta span {{ margin-right: 16px; }}
  .stats {{ display: flex; gap: 16px; margin-bottom: 20px; flex-wrap: wrap; }}
  .stat-card {{ background: #fff; border-radius: 8px; padding: 16px 20px;
                box-shadow: 0 1px 3px rgba(0,0,0,0.08); min-width: 140px; }}
  .stat-card .label {{ font-size: 0.75rem; color: #95a5a6; text-transform: uppercase; }}
  .stat-card .value {{ font-size: 1.4rem; font-weight: 600; color: #2c3e50; }}
  table {{ width: 100%; border-collapse: collapse; background: #fff;
           border-radius: 8px; overflow: hidden;
           box-shadow: 0 1px 3px rgba(0,0,0,0.08); }}
  th {{ background: #2980b9; color: #fff; padding: 10px 12px; text-align: left;
       font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.5px; }}
  td {{ padding: 10px 12px; border-bottom: 1px solid #ecf0f1; font-size: 0.85rem;
       max-width: 400px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
  tr:hover td {{ background: #ebf5fb; }}
  a {{ color: #2980b9; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .budget {{ color: #e67e22; font-weight: 500; white-space: nowrap; }}
  .region {{ color: #27ae60; }}
  .footer {{ margin-top: 20px; text-align: center; color: #bdc3c7; font-size: 0.75rem; }}
</style>
</head>
<body>
<div class="container">
  <h1>{title}</h1>
  <div class="meta">
    <span>关键词: {keyword}</span>
    <span>生成时间: {gen_time}</span>
    <span>数据来源: ggzy.gov.cn</span>
  </div>
  <div class="stats">
    <div class="stat-card"><div class="label">总记录数</div><div class="value">{total}</div></div>
    <div class="stat-card"><div class="label">有效记录</div><div class="value">{valid}</div></div>
    <div class="stat-card"><div class="label">覆盖省份</div><div class="value">{regions}</div></div>
    <div class="stat-card"><div class="label">含预算信息</div><div class="value">{with_budget}</div></div>
  </div>
  <table>
    <thead>
      <tr>
        <th>#</th><th>标题</th><th>日期</th><th>采购人/招标人</th>
        <th>地区</th><th>预算金额</th><th>链接</th>
      </tr>
    </thead>
    <tbody>
{rows}
    </tbody>
  </table>
  <div class="footer">
    Generated by ggzy_bid_scout &middot; OpenClaw &middot; {gen_time}
  </div>
</div>
</body>
</html>
"""


def load_structured_data(input_path: Path) -> dict[str, Any]:
    """加载结构化 JSON 数据。"""
    if not input_path.exists():
        raise FileNotFoundError(f"Structured data not found: {input_path}")
    data = json.loads(input_path.read_text(encoding="utf-8"))
    logger.info("Loaded %d items from %s", len(data.get("items", [])), input_path)
    return data


def _normalize_item(item: dict[str, Any]) -> dict[str, str]:
    """将采集记录规范化为报告输出格式。"""
    date_val = item.get("publish_date", "") or ""
    if " " in date_val:
        date_val = date_val.split(" ")[0]

    return {
        "title": item.get("title", "") or "",
        "date": date_val,
        "issuer": item.get("issuer", "") or "",
        "region": item.get("region", "") or "",
        "budget": item.get("budget", "") or "",
        "detail_url": item.get("detail_url", "") or "",
    }


def export_csv(items: list[dict], output_path: Path) -> Path:
    """导出 CSV 报告。"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    rows = [_normalize_item(it) for it in items]

    with open(output_path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        writer.writeheader()
        writer.writerows(rows)

    logger.info("CSV exported: %s (%d rows)", output_path, len(rows))
    return output_path


def export_json(items: list[dict], meta: dict, output_path: Path) -> Path:
    """导出精简 JSON 报告（不含正文）。"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    rows = [_normalize_item(it) for it in items]

    report = {
        "meta": {
            "keyword": meta.get("keyword", ""),
            "export_time": datetime.now().isoformat(),
            "total": len(rows),
            "source": "ggzy.gov.cn",
        },
        "items": rows,
    }

    output_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    logger.info("JSON exported: %s (%d items)", output_path, len(rows))
    return output_path


def export_html(items: list[dict], meta: dict, output_path: Path) -> Path:
    """导出 HTML 报告。"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    rows = [_normalize_item(it) for it in items]

    keyword = meta.get("keyword", "")
    gen_time = datetime.now().strftime("%Y-%m-%d %H:%M")
    total = len(rows)
    valid = sum(1 for r in rows if r["title"])
    region_set = {r["region"] for r in rows if r["region"]}
    with_budget = sum(1 for r in rows if r["budget"])

    table_rows = []
    for idx, r in enumerate(rows, 1):
        title_escaped = html.escape(r["title"])
        title_short = title_escaped[:80] + "..." if len(title_escaped) > 80 else title_escaped
        url = html.escape(r["detail_url"])

        table_rows.append(
            f'      <tr>'
            f'<td>{idx}</td>'
            f'<td title="{title_escaped}">{title_short}</td>'
            f'<td>{html.escape(r["date"])}</td>'
            f'<td>{html.escape(r["issuer"]) or "-"}</td>'
            f'<td class="region">{html.escape(r["region"])}</td>'
            f'<td class="budget">{html.escape(r["budget"]) or "-"}</td>'
            f'<td><a href="{url}" target="_blank">查看</a></td>'
            f'</tr>'
        )

    html_content = HTML_TEMPLATE.format(
        title=f"招标信息采集报告 — {keyword}",
        keyword=html.escape(keyword),
        gen_time=gen_time,
        total=total,
        valid=valid,
        regions=len(region_set),
        with_budget=with_budget,
        rows="\n".join(table_rows),
    )

    output_path.write_text(html_content, encoding="utf-8")
    logger.info("HTML exported: %s (%d rows)", output_path, len(rows))
    return output_path


def export_all(
    input_name: str = "bid_data",
    output_name: str = "bid_report",
) -> dict[str, str]:
    """
    导出全部三种格式的报告。

    Args:
        input_name: 输入文件名前缀（data/structured/{name}.json）
        output_name: 输出文件名前缀

    Returns:
        各格式的输出路径
    """
    input_path = STRUCTURED_DIR / f"{input_name}.json"
    data = load_structured_data(input_path)
    items = data.get("items", [])
    meta = data.get("meta", {})

    if not items:
        raise ValueError(f"No items found in {input_path}")

    csv_path = export_csv(items, REPORTS_DIR / f"{output_name}.csv")
    json_path = export_json(items, meta, REPORTS_DIR / f"{output_name}.json")
    html_path = export_html(items, meta, REPORTS_DIR / f"{output_name}.html")

    return {
        "csv": str(csv_path),
        "json": str(json_path),
        "html": str(html_path),
        "total_items": len(items),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Export bid data to CSV/HTML/JSON reports")
    parser.add_argument("--input", default="bid_data",
                        help="Input file name prefix (from data/structured/)")
    parser.add_argument("--output", default="bid_report",
                        help="Output file name prefix (to data/reports/)")
    parser.add_argument("--format", choices=["csv", "html", "json", "all"], default="all",
                        help="Export format (default: all)")
    args = parser.parse_args()

    input_path = STRUCTURED_DIR / f"{args.input}.json"
    data = load_structured_data(input_path)
    items = data.get("items", [])
    meta = data.get("meta", {})

    if not items:
        print(f"No items found in {input_path}")
        sys.exit(1)

    results = {}
    if args.format in ("csv", "all"):
        results["csv"] = str(export_csv(items, REPORTS_DIR / f"{args.output}.csv"))
    if args.format in ("json", "all"):
        results["json"] = str(export_json(items, meta, REPORTS_DIR / f"{args.output}.json"))
    if args.format in ("html", "all"):
        results["html"] = str(export_html(items, meta, REPORTS_DIR / f"{args.output}.html"))

    print(f"\n{'='*60}")
    print("Export Summary")
    print(f"{'='*60}")
    print(f"  Source: {input_path}")
    print(f"  Items: {len(items)}")
    for fmt, path in results.items():
        print(f"  {fmt.upper()}: {path}")


if __name__ == "__main__":
    main()
